[package]
name = "port-scanner"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
futures = "0.3.25"
clap = { version = "4.0.26", features = ["derive"] }
